Repository ValFraNath/apothiquiz, pull requests merged in 2021-01, with the labels that each got.

#134 Improve the question generator
  client/src/components/layouts/Train.js
  client/src/components/quizz/Answers.js
  client/src/styles/base/_main.scss
  server/controllers/question.js
  server/modules/data_importer/data_importer.js
  server/modules/question_generator_scripts/question_CM1.sql
  server/modules/question_generator_scripts/question_CM2.sql
  server/modules/question_generator_scripts/question_MC1.sql
  server/modules/question_generator_scripts/question_MC2.sql
  server/modules/question_generator_scripts/question_MP.sql
  server/modules/question_generator_scripts/question_MS1.sql
  server/modules/question_generator_scripts/question_MS2.sql
  server/modules/question_generator_scripts/question_PM.sql
  server/modules/question_generator_scripts/question_SM1.sql
  server/modules/question_generator_scripts/question_SM2.sql
  server/test/api.test.js
  server/test/csv_parser/parser.test.js
  server/test/data_importer/data_importer.test.js
  server/test/data_importer/expectations.js
  server/test/data_importer/files/molecules.csv
  server/test/database.test.js
  server/test/index.test.js
  server/test/question.test.js
  server/test/user.test.js
Labels: Backend, Database

#146 Update database : Duels procedures and adjustments
  server/db/database.js
  server/db/updates/db_20210121_to_20210125.sql
  server/test/database.test.js
Labels: Database

#147 Update database : Users stats
  server/controllers/user.js
  server/db/database.js
  server/db/updates/db_20210125_to_20210126.sql
  server/test/database.test.js
Labels: Database

#148 Fix quiz layout
  client/src/components/layouts/Train.js
  client/src/components/quizz/Answers.js
  client/src/components/quizz/Question.js
  client/src/styles/base/_variables.scss
  client/src/styles/layouts/_quiz.scss
  server/package-lock.json
Labels: Frontend, bug

#151 Fix bad random
  server/controllers/question.js
Labels: Backend, bug

#152 Use prop-types instead of proptypes, and files reorganization
  client/package-lock.json
  client/package.json
  client/src/App.js
  client/src/components/Avatar.js
  client/src/components/ChooseAvatar.js
  client/src/components/SpriteSheet.js
  client/src/components/buttons/ButtonCircle.js
  client/src/components/buttons/ButtonDefault.js
  client/src/components/buttons/ButtonFullWidth.js
  client/src/components/quiz/Answers.js
  client/src/components/quiz/Message.js
  client/src/components/quiz/Question.js
  client/src/components/quiz/Timer.js
  client/src/components/system/InstallApp.js
  client/src/components/system/TopBar.js
  client/src/pages/About.js
  client/src/pages/Login.js
  client/src/pages/Menu.js
  client/src/pages/Profile.js
  client/src/pages/Train.js
  client/src/styles/base/_App.scss
  client/src/styles/base/_mixins.scss
  client/src/styles/base/_shared.scss
  client/src/styles/base/_variables.scss
  client/src/styles/components/_Avatar.scss
  client/src/styles/components/_ChooseAvatar.scss
  client/src/styles/components/_TopBar.scss
  client/src/styles/components/_messages.scss
  client/src/styles/components/_quiz.scss
  client/src/styles/components/_userBadge.scss
  client/src/styles/layouts/App.scss
  client/src/styles/pages/_About.scss
  client/src/styles/pages/_Login.scss
  client/src/styles/styles.scss
  client/src/test/App.test.js
  client/src/test/Login.test.js
  client/src/test/SpriteSheet.test.js
  client/src/test/Train.test.js
Labels: Frontend

#153 New githook, formatted to printWidth=100 and updated links
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/PULL_REQUEST_TEMPLATE.md
  .prettierrc
  README.md
  client/src/components/Avatar.js
  client/src/components/ChooseAvatar.js
  client/src/components/SpriteSheet.js
  client/src/pages/About.js
  client/src/pages/Train.js
  client/src/service-worker.js
  client/src/services/auth.service.js
  githooks/post-merge.sh
  githooks/pre-commit.sh
  githooks/prepare-commit-msg.sh
  githooks/setup-hooks.sh
  server/controllers/api.js
  server/controllers/duels.js
  server/controllers/question.js
  server/controllers/user.js
  server/db/database.js
  server/modules/data_importer/csv_parser/HeaderChecker.js
  server/modules/data_importer/csv_parser/Parser.js
  server/modules/data_importer/data_importer.js
  server/test/csv_parser/expectations.js
  server/test/csv_parser/parser.test.js
  server/test/data_importer/data_importer.test.js
  server/test/data_importer/expectations.js
  server/test/database.test.js
  server/test/duel.test.js
  server/test/question.test.js
  server/test/user.test.js
Labels: CI/CD/Github

#144 Home page (for connected users)
  client/src/App.js
  client/src/components/Avatar.js
  client/src/components/system/TopBar.js
  client/src/images/attente.png
  client/src/images/fight.png
  client/src/pages/About.js
  client/src/pages/HomePage.js
  client/src/pages/Login.js
  client/src/pages/Train.js
  client/src/styles/components/_buttons.scss
  client/src/styles/pages/_HomePage.scss
  client/src/styles/styles.scss
  server/controllers/user.js
  server/routes/api.route.js
  server/routes/react.route.js
  server/test/user.test.js
Labels: Frontend

#157 Redirect / to Homepage
  client/src/pages/Menu.js
Labels: Frontend, bug

#160 Fix the random of good answer index (I'm stupid)
  server/controllers/question.js
Labels: bug

#154 Logger & better errors handling
  .gitignore
  server/controllers/api.js
  server/controllers/duels.js
  server/controllers/question.js
  server/controllers/user.js
  server/db/database.js
  server/global/HttpResponseWrapper.js
  server/global/Logger.js
  server/global/data_importer/csv_parser/FileStructure.js
  server/global/data_importer/csv_parser/HeaderChecker.js
  server/global/data_importer/csv_parser/MoleculeList.js
  server/global/data_importer/csv_parser/MoleculesClassification.js
  server/global/data_importer/csv_parser/MoleculesProperty.js
  server/global/data_importer/csv_parser/Parser.js
  server/global/data_importer/csv_parser/ParserSpecifications.js
  server/global/data_importer/csv_parser/Reader.js
  server/global/data_importer/data_importer.js
  server/global/question_generator_scripts/question_CM1.sql
  server/global/question_generator_scripts/question_CM2.sql
  server/global/question_generator_scripts/question_MC1.sql
  server/global/question_generator_scripts/question_MC2.sql
  server/global/question_generator_scripts/question_MP.sql
  server/global/question_generator_scripts/question_MS1.sql
  server/global/question_generator_scripts/question_MS2.sql
  server/global/question_generator_scripts/question_PM.sql
  server/global/question_generator_scripts/question_SM1.sql
  server/global/question_generator_scripts/question_SM2.sql
  server/index.js
  server/middlewares/auth.middleware.js
  server/middlewares/error.middleware.js
  server/test/api.test.js
  server/test/csv_parser/parser.test.js
  server/test/data_importer/data_importer.test.js
  server/test/database.test.js
Labels: Backend

#159 Create duel
  client/src/App.js
  client/src/pages/CreateDuel.js
  client/src/pages/HomePage.js
  client/src/styles/pages/_CreateDuel.scss
  client/src/styles/styles.scss
  server/controllers/user.js
  server/routes/api.route.js
  server/routes/react.route.js
Labels: Frontend

#162 Duel overview page
  client/src/App.js
  client/src/components/Avatar.js
  client/src/components/ProtectedRoute.js
  client/src/pages/DuelOverview.js
  client/src/pages/HomePage.js
  client/src/styles/components/_buttons.scss
  client/src/styles/pages/_DuelOverview.scss
  client/src/styles/pages/_HomePage.scss
  client/src/styles/styles.scss
  server/routes/react.route.js
Labels: Frontend

#161 Duel view
  client/src/App.js
  client/src/components/ProtectedRoute.js
  client/src/components/quiz/Question.js
  client/src/pages/CreateDuel.js
  client/src/pages/Duel.js
  client/src/pages/DuelOverview.js
  client/src/pages/HomePage.js
  client/src/pages/Menu.js
  client/src/pages/Train.js
  client/src/styles/base/_App.scss
  client/src/styles/base/_variables.scss
  client/src/styles/components/_quiz.scss
  client/src/styles/pages/_Duel.scss
  client/src/styles/pages/_DuelOverview.scss
  client/src/styles/pages/_HomePage.scss
  client/src/styles/pages/_Train.scss
  client/src/styles/styles.scss
  server/controllers/duels.js
  server/routes/react.route.js
  server/test/duel.test.js
Labels: Frontend

#165 Fix ios zoom on input
  client/src/styles/base/_shared.scss
Labels: bug

#164 Add format check to ci
  .github/workflows/node.js.yml
  client/package.json
  githooks/pre-commit.sh
  server/package.json
Labels: CI/CD/Github

#166 Fix search and add finished duels
  client/package.json
  client/src/pages/CreateDuel.js
  client/src/pages/HomePage.js
  client/src/styles/pages/_HomePage.scss
  server/package.json
Labels: Frontend, bug, enhancement

#167 Homepage improvements
  client/src/pages/HomePage.js
Labels: Frontend

#169 Use scss features because if not its useless
  client/src/components/ChooseAvatar.js
  client/src/styles/base/_variables.module.scss
  client/src/styles/components/_Avatar.scss
  client/src/styles/components/_TopBar.scss
  client/src/styles/pages/_DuelOverview.scss
  client/src/styles/pages/_Profile.scss
  client/src/styles/styles.scss
Labels: Frontend

#168 Data importation refactoring
  server/global/csv_reader/FileStructure.js
  server/global/csv_reader/HeaderChecker.js
  server/global/csv_reader/ParserSpecifications.js
  server/global/csv_reader/Reader.js
  server/global/data_importer/csv_parser/Parser.js
  server/global/data_importer/csv_parser/Reader.js
  server/global/data_importer/dataImporter.js
  server/global/molecules_parser/MoleculeList.js
  server/global/molecules_parser/MoleculesClassification.js
  server/global/molecules_parser/MoleculesProperty.js
  server/global/molecules_parser/Parser.js
  server/test/csv_parser/parser.test.js
  server/test/data_importer/dataImporter.test.js
Labels: Backend

#173 Fix random avatar
  client/src/components/ChooseAvatar.js
  client/src/styles/base/_variables.module.scss
  client/src/styles/components/_Avatar.scss
Labels: Frontend, bug
