Repository ValFraNath/apothiquiz, pull requests merged in 2021-03, with the labels that each got.

#205 s/glowing-octo-guacamole/guacamole/g
  .github/PULL_REQUEST_TEMPLATE.md
  .github/workflows/node.js.yml
  README.md
  client/public/index.html
  client/src/pages/About.js
  client/src/styles/base/_shared.scss
  server/controllers/imagesImporter.js
  server/controllers/moleculesImporter.js
  server/controllers/usersImportation.js
  server/db/create_database.sql
  server/db/database.js
  server/package.json
  server/test/database.test.js
  server/test/duel.test.js
  server/test/images_importation/imagesAnalyzer.test.js
  server/test/images_importation/imagesImporter.test.js
  server/test/images_importation/importation_route/importImages.test.js
  server/test/molecules_importation/analyzer/moleculesAnalyzer.test.js
  server/test/molecules_importation/importation_route/importMolecule.test.js
  server/test/molecules_importation/importer/moleculesImporter.test.js
  server/test/question.test.js
  server/test/user.test.js
  server/test/users_importation/importation_route/importUsers.test.js
  server/test/users_importation/importer/usersImporter.test.js
Labels: CI/CD/Github, documentation

#207 Asynchronous code refactoring
  client/src/pages/About.js
  client/src/pages/Admin.js
  client/src/pages/Duel.js
  client/src/pages/DuelCreate.js
  client/src/pages/Train.js
  client/src/services/auth.service.js
  client/src/test/Train.test.js
  client/src/utils/queryDuels.js
  client/src/utils/queryUsers.js
  server/controllers/api.js
  server/controllers/config.js
  server/controllers/duels.js
  server/controllers/imagesImporter.js
  server/controllers/moleculesImporter.js
  server/controllers/question.js
  server/controllers/user.js
  server/controllers/usersImportation.js
  server/db/database.js
  server/global/HttpControllerWrapper.js
  server/global/Logger.js
  server/global/csv_reader/reader.js
  server/global/files.js
  server/global/images_importation/imagesAnayzer.js
  server/global/images_importation/imagesImporter.js
  server/global/molecules_importation/moleculesImporter.js
  server/global/molecules_importation/moleculesParser.js
  server/global/users_importation/usersImporter.js
  server/global/users_importation/usersParser.js
  server/index.js
  server/middlewares/auth.middleware.js
  server/middlewares/error.middleware.js
  server/middlewares/multer.middleware.js
  server/routes/api.route.js
  server/test/config/config.test.js
  server/test/images_importation/importation_route/importImages.test.js
  server/test/index.test.js
  server/test/question.test.js
Labels: Backend, enhancement

#213 Rename images-molecules.zip, not .csv
  client/src/pages/Admin.js
Labels: Frontend, bug

#206 Reduce client size
  client/package-lock.json
  client/src/App.js
  client/src/components/ProtectedRoute.js
  client/src/images/attente.png
  client/src/images/bg_menu.jpg
  client/src/images/bg_menu.png
  client/src/images/fight.png
  client/src/images/information_crop.png
  client/src/images/timer_colors.png
  client/src/images/timer_stroke.png
  client/src/styles/pages/_HomePage.scss
  client/src/styles/pages/_Menu.scss
Labels: Frontend

#212 Cron cron cron
  client/src/pages/Admin.js
  server/controllers/config.js
  server/controllers/duels.js
  server/db/database.js
  server/db/updates/db_20210219_to_20210222.sql
  server/db/updates/db_20210222_to_20210302.sql
  server/files-script/cron-tasks.js
  server/global/dateUtils.js
  server/index.js
  server/package-lock.json
  server/package.json
  server/test/database.test.js
Labels: Backend, Database

#216 Fix cron
  server/db/updates/db_20210222_to_20210302.sql
  server/files-script/cron-tasks.js
Labels: Backend, bug

#211 Improve authentication system
  .github/workflows/node.js.yml
  client/package.json
  client/src/App.js
  client/src/components/ProtectedRoute.js
  client/src/pages/Admin.js
  client/src/pages/Profile.js
  client/src/services/auth.service.js
  server/controllers/config.js
  server/controllers/duels.js
  server/controllers/user.js
  server/db/database.js
  server/db/updates/db_20210302_to_20210306.sql
  server/global/Logger.js
  server/global/Tokens.js
  server/index.js
  server/middlewares/auth.middleware.js
  server/package-lock.json
  server/package.json
  server/routes/api.route.js
  server/test/config/config.test.js
  server/test/database.test.js
  server/test/images_importation/importation_route/importImages.test.js
  server/test/index.test.js
  server/test/molecules_importation/importation_route/importMolecule.test.js
  server/test/user.test.js
  server/test/users_importation/importation_route/importUsers.test.js
Labels: Backend, Database, Frontend

#218 One duel at a time !
  server/controllers/duels.js
  server/test/duel.test.js
Labels: Backend

#224 Remove last glowing reference
  client/public/manifest.json
Labels: bug

#223 Fix molecules analyzer
  server/db/database.js
  server/db/updates/db_20210306_to_20210311.sql
  server/global/molecules_importation/moleculesAnalyzer.js
  server/global/molecules_importation/moleculesImporter.js
  server/test/database.test.js
  server/test/molecules_importation/analyzer/moleculesAnalyzer.test.js
  server/test/question.test.js
  server/test/required_data/molecules.sql
Labels: Backend, Database

#222 Improve UI
  client/src/App.js
  client/src/pages/DuelCreate.js
  client/src/pages/Profile.js
  client/src/setupTests.js
  client/src/styles/base/_App.scss
  client/src/styles/base/_shared.scss
  client/src/styles/base/_variables.module.scss
  client/src/styles/components/_TopBar.scss
  client/src/styles/components/_buttons.scss
  client/src/styles/components/_quiz.scss
  client/src/styles/pages/_Duel.scss
  client/src/styles/pages/_DuelCreate.scss
  client/src/styles/pages/_DuelOverview.scss
  client/src/styles/pages/_HomePage.scss
  client/src/styles/pages/_Profile.scss
  client/src/styles/pages/_Train.scss
  client/src/test/App.test.js
Labels: Frontend, bug, enhancement

#225 Update SW
  client/src/service-worker.js
Labels: Frontend, bug

#219 Generate fake data script for load-testing
  server/controllers/duels.js
  server/db/fill-fake-data.js
  server/package-lock.json
  server/package.json
Labels: Backend

#231 Better question wording
  client/src/pages/Login.js
  client/src/test/App.test.js
  client/src/test/Train.test.js
  server/controllers/question.js
  server/global/molecules_importation/moleculesAnalyzer.js
  server/test/mocks/rounds.mock.json
Labels: Backend, Frontend

#226 Importation refactoring
  server/controllers/imagesImporter.js
  server/controllers/moleculesImporter.js
  server/controllers/usersImportation.js
  server/db/database.js
  server/global/csv_reader/FileStructure.js
  server/global/images_importation/ImagesList.js
  server/global/images_importation/imagesAnayzer.js
  server/global/images_importation/imagesImporter.js
  server/global/importationUtils.js
  server/global/molecules_importation/Classification.js
  server/global/molecules_importation/MoleculeList.js
  server/global/molecules_importation/MoleculesClassification.js
  server/global/molecules_importation/MoleculesList.js
  server/global/molecules_importation/MoleculesProperty.js
  server/global/molecules_importation/Property.js
  server/global/molecules_importation/moleculesAnalyzer.js
  server/global/molecules_importation/moleculesImporter.js
  server/global/molecules_importation/moleculesParser.js
  server/global/users_importation/UsersList.js
  server/global/users_importation/usersAnalyzer.js
  server/global/users_importation/usersImporter.js
  server/global/users_importation/usersParser.js
  server/test/config/config.test.js
  server/test/images_importation/imagesAnalyzer.test.js
  server/test/images_importation/imagesImporter.test.js
  server/test/images_importation/importation_route/importImages.test.js
  server/test/molecules_importation/analyzer/files/tooLongNames.csv
  server/test/molecules_importation/analyzer/moleculesAnalyzer.test.js
  server/test/molecules_importation/importer/moleculesImporter.test.js
  server/test/molecules_importation/parser/expectations.js
  server/test/molecules_importation/parser/files/molecules.csv
  server/test/molecules_importation/parser/files/molecules_v2.csv
  server/test/molecules_importation/parser/moleculesParser.test.js
  server/test/molecules_importation/parser/snapshots/empty.json
  server/test/molecules_importation/parser/snapshots/molecules.json
  server/test/molecules_importation/parser/snapshots/molecules_v2.json
  server/test/molecules_importation/parser/snapshots/moved_columns.json
  server/test/molecules_importation/parser/snapshots/only_dci.json
  server/test/molecules_importation/parser/snapshots/sample.json
  server/test/molecules_importation/parser/snapshots/separated_rows.json
  server/test/users_importation/analyzer/files/invalid_admin.csv
  server/test/users_importation/analyzer/usersAnalyzer.test.js
  server/test/users_importation/importer/usersImporter.test.js
  server/test/users_importation/parser/usersParser.test.js
Labels: Backend

#235 console.info in fake-data script
  server/db/fill-fake-data.js
Labels: Backend

#229 Improve UI for finished duels
  client/src/pages/DuelOverview.js
  client/src/pages/HomePage.js
  client/src/styles/pages/_DuelOverview.scss
  client/src/styles/pages/_HomePage.scss
  client/src/utils/queryDuels.js
  server/controllers/duels.js
  server/package-lock.json
Labels: Frontend, enhancement

#233 Add animations for fight, wait, loading, error
  .github/PULL_REQUEST_TEMPLATE.md
  client/package.json
  client/src/components/SpriteSheet.js
  client/src/components/animations/AnimAction.js
  client/src/components/animations/AnimLoop.js
  client/src/components/animations/AnimTransition.js
  client/src/components/status/FloatingError.js
  client/src/components/status/Loading.js
  client/src/components/status/PageError.js
  client/src/components/system/TopBar.js
  client/src/images/attente.png
  client/src/images/error.png
  client/src/images/fight.png
  client/src/images/sprites/fight-action.png
  client/src/images/sprites/fight-loop.png
  client/src/images/sprites/loading-loop.png
  client/src/images/sprites/network-status.png
  client/src/images/sprites/waiting-action.png
  client/src/images/sprites/waiting-loop.png
  client/src/pages/HomePage.js
  client/src/styles/components/_Animations.scss
  client/src/styles/components/_Status.scss
  client/src/styles/pages/_HomePage.scss
  client/src/styles/styles.scss
  client/src/test/SpriteSheet.test.js
  githooks/pre-commit.sh
Labels: Frontend

#237 Add links to our webpages in README
  README.md
Labels: documentation

#228 Question with images
  client/src/components/quiz/Answers.js
  client/src/components/quiz/Question.js
  client/src/pages/Duel.js
  client/src/pages/Train.js
  client/src/styles/components/_quiz.scss
  server/controllers/question.js
  server/global/question_generator_scripts/question_IM.sql
  server/global/question_generator_scripts/question_MI.sql
  server/test/duel.test.js
  server/test/images_importation/importation_route/importImages.test.js
  server/test/index.test.js
  server/test/question.test.js
  server/test/required_data/images/cobicistat.png
  server/test/required_data/images/daclatasvir.png
  server/test/required_data/images/darunavir.png
  server/test/required_data/images/dolutegravir.png
  server/test/required_data/images/doravirine.png
  server/test/required_data/images/efavirenz.png
Labels: Backend, Database, Frontend

#234 Improve Admin Interface
  client/src/pages/Admin.js
  client/src/styles/pages/_Admin.scss
  server/routes/api.route.js
Labels: Frontend

#241 Reorganize server api routes
  server/index.js
  server/routes/api.route.js
  server/routes/config.route.js
  server/routes/duels.route.js
  server/routes/files.route.js
  server/routes/import.route.js
  server/routes/react.route.js
  server/routes/users.route.js
Labels: backend

#245 Rename the molecule validation regex
  server/global/molecules_importation/MoleculesList.js
Labels: backend

#242 Fix new animations: use JS animations instead of CSS
  client/src/components/animations/AnimLoop.js
  client/src/components/animations/AnimTransition.js
  client/src/components/status/Loading.js
  client/src/components/system/TopBar.js
  client/src/images/sprites/fight-action-240.png
  client/src/images/sprites/fight-action.png
  client/src/images/sprites/fight-loop-240.png
  client/src/images/sprites/fight-loop.png
  client/src/images/sprites/loading-loop-300.png
  client/src/images/sprites/loading-loop.png
  client/src/images/sprites/network-status-60.png
  client/src/images/sprites/waiting-action-120.png
  client/src/images/sprites/waiting-action.png
  client/src/images/sprites/waiting-loop-120.png
  client/src/images/sprites/waiting-loop.png
  client/src/pages/HomePage.js
Labels: frontend

#246 Api messages translation
  server/controllers/api.js
  server/controllers/duels.js
  server/controllers/imagesImporter.js
  server/controllers/moleculesImporter.js
  server/controllers/question.js
  server/controllers/user.js
  server/controllers/usersImportation.js
  server/global/images_importation/ImagesList.js
  server/test/api.test.js
Labels: backend

#247 Redirect to existing duel when creating an existing one
  client/src/pages/DuelCreate.js
  client/src/utils/configuredQueryClient.js
  client/src/utils/queryUsers.js
  server/controllers/duels.js
  server/controllers/user.js
  server/test/duel.test.js
  server/test/index.test.js
  server/test/user.test.js
Labels: backend, frontend

#248 Fix bad users stats increment
  server/controllers/duels.js
Labels: backend, bug

#249 Auto logout in case of bad authentication
  client/src/App.js
  client/src/services/auth.service.js
Labels: frontend

#250 Update generation script to match API changes
  server/db/fill-fake-data.js
Labels: backend

#251 Fix for good the cache of duelCreate
  client/src/utils/configuredQueryClient.js
  client/src/utils/queryUsers.js
Labels: bug, frontend

#253 Generate data script cleanup
  server/db/fill-fake-data.js
Labels: backend

#258 Rename all JSX client files to .jsx
  client/src/App.jsx
  client/src/components/Avatar.jsx
  client/src/components/AvatarChooser.jsx
  client/src/components/Plural.jsx
  client/src/components/ProtectedRoute.jsx
  client/src/components/animations/AnimAction.jsx
  client/src/components/animations/AnimLoop.jsx
  client/src/components/animations/AnimTransition.jsx
  client/src/components/buttons/ButtonCircle.jsx
  client/src/components/buttons/ButtonDefault.jsx
  client/src/components/buttons/ButtonFullWidth.jsx
  client/src/components/quiz/Answers.jsx
  client/src/components/quiz/DuelResults.jsx
  client/src/components/quiz/Message.jsx
  client/src/components/quiz/Question.jsx
  client/src/components/quiz/Timer.jsx
  client/src/components/status/FloatingError.jsx
  client/src/components/status/Loading.jsx
  client/src/components/status/PageError.jsx
  client/src/components/system/InstallApp.jsx
  client/src/components/system/TopBar.jsx
  client/src/index.jsx
  client/src/pages/About.jsx
  client/src/pages/Admin.jsx
  client/src/pages/Duel.jsx
  client/src/pages/DuelCreate.jsx
  client/src/pages/DuelOverview.jsx
  client/src/pages/HomePage.jsx
  client/src/pages/Login.jsx
  client/src/pages/Menu.jsx
  client/src/pages/Profile.jsx
  client/src/pages/Train.jsx
Labels: frontend

#256 Prevent cheating
  client/src/App.jsx
  client/src/components/ProtectedRoute.jsx
  client/src/pages/Admin.jsx
  client/src/pages/Duel.jsx
  client/src/pages/DuelOverview.jsx
  client/src/pages/Login.jsx
  client/src/pages/Menu.jsx
  client/src/pages/Profile.jsx
  client/src/utils/antiCheat.js
  client/src/utils/authentication.js
  client/src/utils/queryDuels.js
Labels: backend

#261 Improve dark mode : profile
  client/src/styles/components/_ChooseAvatar.scss
Labels: enhancement, frontend

#257 Update time display on duels
  client/src/components/RemainingTime.jsx
  client/src/pages/DuelOverview.jsx
  client/src/pages/HomePage.jsx
  client/src/styles/components/_RemainingTime.scss
  client/src/styles/styles.scss
  client/src/utils/handleDates.js
Labels: enhancement, frontend

#262 Update service-worker
  client/package-lock.json
  client/package.json
  client/src/App.jsx
  client/src/service-worker.js
Labels: backend, bug, enhancement

#263 Add MIT license
  LICENSE
Labels: documentation

#265 API: Fix challengeable users request
  server/controllers/user.js
  server/db/database.js
  server/db/updates/db_20210311_to_20210326.sql
  server/test/user.test.js
Labels: backend, bug

#264 Frontend issue
  client/src/components/RemainingTime.jsx
  client/src/styles/pages/_HomePage.scss
Labels: bug, frontend

#266 Update sw faster
  client/src/service-worker.js
Labels: backend, enhancement

#267 Improve cron script
  server/files-script/cron-tasks.js
Labels: backend, enhancement
