Repository ValFraNath/apothiquiz, pull requests merged in 2021-04, with the labels that each got.

#273 Choose the database used according to the NODE_ENV
  .github/workflows/node.js.yml
  server/db/database.js
  server/index.js
  server/package.json
Labels: backend

#268 New topbar
  client/src/pages/About.jsx
  client/src/pages/Menu.jsx
  client/src/styles/base/_App.scss
  client/src/styles/base/_variables.module.scss
  client/src/styles/components/_TopBar.scss
  client/src/styles/pages/_Menu.scss
Labels: enhancement, frontend

#277 Imrove dark mode
  client/src/styles/base/_App.scss
Labels: frontend

#278 Remove tests from pre-commit hook, the CI will take care of this
  githooks/pre-commit.sh
Labels: CI/CD/Github

#280 Final app name : Apothiquiz
  .github/PULL_REQUEST_TEMPLATE.md
  .github/workflows/node.js.yml
  .gitignore
  README.md
  client/public/index.html
  client/public/manifest.json
  client/src/components/system/TopBar.jsx
  client/src/pages/About.jsx
  client/src/pages/Admin.jsx
  client/src/service-worker.js
  client/src/styles/pages/_About.scss
  githooks/prepare-commit-msg.sh
  server/controllers/imagesImporter.js
  server/controllers/moleculesImporter.js
  server/controllers/usersImportation.js
  server/db/create_database.sql
  server/index.js
Labels: backend, documentation, frontend
