Repository ValFraNath/apothiquiz, pull requests merged in 2021-02, with the labels that each got.

#174 Create the data analyzer
  package-lock.json
  server/global/data_analyzer/analyzer.js
  server/global/data_importer/dataImporter.js
  server/package-lock.json
  server/package.json
  server/test/analyzer/analyzer.test.js
  server/test/analyzer/files/badTypes.csv
  server/test/analyzer/files/duplicatesMolecules.csv
  server/test/analyzer/files/duplicatesNodes.csv
  server/test/analyzer/files/molecules.csv
  server/test/analyzer/files/tooLongNames.csv
  server/test/analyzer/files/worst.csv
Labels: Backend

#180 Create the molecules importation routes
  .gitignore
  server/controllers/api.js
  server/controllers/duels.js
  server/controllers/moleculesImporter.js
  server/controllers/question.js
  server/db/database.js
  server/global/HttpResponseWrapper.js
  server/global/Logger.js
  server/global/data_importer/csv_parser/Parser.js
  server/global/data_importer/csv_parser/Reader.js
  server/global/molecules_analyzer/moleculesAnalyzer.js
  server/global/molecules_importer/moleculesImporter.js
  server/index.js
  server/middlewares/multer.middleware.js
  server/package-lock.json
  server/package.json
  server/routes/api.route.js
  server/test/molecules_analyzer/files/badTypes.csv
  server/test/molecules_analyzer/files/duplicatesMolecules.csv
  server/test/molecules_analyzer/files/duplicatesNodes.csv
  server/test/molecules_analyzer/files/molecules.csv
  server/test/molecules_analyzer/files/tooLongNames.csv
  server/test/molecules_analyzer/files/worst.csv
  server/test/molecules_analyzer/moleculesAnalyzer.test.js
  server/test/molecules_importation_route/files/bad.csv
  server/test/molecules_importation_route/files/little_sample.csv
  server/test/molecules_importation_route/files/molecules.csv
  server/test/molecules_importation_route/files/molecules.xlsx
  server/test/molecules_importation_route/files/molecules_false.csv
  server/test/molecules_importation_route/importMolecule.test.js
  server/test/molecules_importer/expectations.js
  server/test/molecules_importer/files/molecules.csv
  server/test/molecules_importer/moleculesImporter.test.js
  server/test/molecules_parser/expectations.js
  server/test/molecules_parser/files/bad_formatted_files/bad_grouped_classification.csv
  server/test/molecules_parser/files/bad_formatted_files/bad_grouped_property.csv
  server/test/molecules_parser/files/bad_formatted_files/bad_hierarchical_levels.csv
  server/test/molecules_parser/files/bad_formatted_files/empty_column.csv
  server/test/molecules_parser/files/bad_formatted_files/empty_file.csv
  server/test/molecules_parser/files/bad_formatted_files/invalid_column.csv
  server/test/molecules_parser/files/bad_formatted_files/missing_classification.csv
  server/test/molecules_parser/files/bad_formatted_files/missing_side_effects.csv
  server/test/molecules_parser/files/bad_formatted_files/missing_skeletal_formula.csv
  server/test/molecules_parser/files/bad_formatted_files/several_errors.csv
  server/test/molecules_parser/files/molecules.csv
  server/test/molecules_parser/files/molecules_empty.csv
  server/test/molecules_parser/files/molecules_little_sample.csv
  server/test/molecules_parser/files/molecules_moved_columns.csv
  server/test/molecules_parser/files/molecules_only_dci.csv
  server/test/molecules_parser/files/molecules_separated_rows.csv
  server/test/molecules_parser/moleculesParser.test.js
  server/test/molecules_parser/snapshots/empty.json
  server/test/molecules_parser/snapshots/molecules.json
  server/test/molecules_parser/snapshots/moved_columns.json
  server/test/molecules_parser/snapshots/only_dci.json
  server/test/molecules_parser/snapshots/sample.json
  server/test/molecules_parser/snapshots/separated_rows.json
Labels: Backend

#182 Admin view V1
  client/src/App.js
  client/src/pages/Admin.js
  client/src/styles/base/_App.scss
  client/src/styles/components/_ChooseAvatar.scss
  client/src/styles/pages/_Admin.scss
  client/src/styles/styles.scss
  server/controllers/moleculesImporter.js
  server/global/molecules_analyzer/moleculesAnalyzer.js
  server/index.js
  server/middlewares/multer.middleware.js
  server/package-lock.json
  server/routes/api.route.js
  server/routes/react.route.js
  server/test/molecules_analyzer/moleculesAnalyzer.test.js
  server/test/molecules_importation_route/importMolecule.test.js
Labels: Frontend

#184 Fix UI issues
  client/package.json
  client/src/styles/base/_App.scss
  client/src/styles/base/_shared.scss
Labels: Frontend, bug

#183 Improve question scripts
  client/src/pages/Train.js
  server/controllers/question.js
  server/global/Logger.js
  server/global/question_generator_scripts/question_CM.sql
  server/global/question_generator_scripts/question_CM1.sql
  server/global/question_generator_scripts/question_MC.sql
  server/global/question_generator_scripts/question_MC1.sql
  server/global/question_generator_scripts/question_MP.sql
  server/global/question_generator_scripts/question_MS.sql
  server/global/question_generator_scripts/question_MS1.sql
  server/global/question_generator_scripts/question_PM.sql
  server/global/question_generator_scripts/question_SM.sql
  server/global/question_generator_scripts/question_SM1.sql
  server/test/duel.test.js
  server/test/question.test.js
Labels: Database

#185 Fix the fix #184
  client/src/pages/Menu.js
  client/src/styles/components/_buttons.scss
  client/src/styles/pages/_Menu.scss
Labels: Frontend, bug

#186 Use defaultProps for <Avatar>
  client/src/components/Avatar.js
  client/src/components/system/TopBar.js
  client/src/pages/Profile.js
Labels: Frontend

#190 Improve DuelOverview and Avatar usage
  client/package.json
  client/src/components/Avatar.js
  client/src/components/quiz/DuelResults.js
  client/src/components/system/TopBar.js
  client/src/pages/CreateDuel.js
  client/src/pages/DuelOverview.js
  client/src/pages/HomePage.js
  client/src/pages/Profile.js
  client/src/styles/components/_quiz.scss
  client/src/styles/pages/_DuelOverview.scss
Labels: Frontend

#191 Use special database for tests
  .github/workflows/node.js.yml
  server/package.json
Labels: CI/CD/Github

#193 Users importation
  .gitignore
  client/src/pages/Admin.js
  server/controllers/duels.js
  server/controllers/imagesImporter.js
  server/controllers/moleculesImporter.js
  server/controllers/user.js
  server/controllers/usersImportation.js
  server/db/database.js
  server/db/updates/db_20210211_to_20210219.sql
  server/global/csv_reader/ColumnSpecification.js
  server/global/csv_reader/FileStructure.js
  server/global/csv_reader/HeaderChecker.js
  server/global/csv_reader/reader.js
  server/global/files.js
  server/global/images_importation/imagesAnayzer.js
  server/global/images_importation/imagesImporter.js
  server/global/importationUtils.js
  server/global/molecules_importation/moleculesAnalyzer.js
  server/global/molecules_importation/moleculesImporter.js
  server/global/molecules_importation/moleculesParser.js
  server/global/users_importation/usersAnalyzer.js
  server/global/users_importation/usersImporter.js
  server/global/users_importation/usersParser.js
  server/index.js
  server/package-lock.json
  server/package.json
  server/routes/api.route.js
  server/test/database.test.js
  server/test/images_importation/importation_route/importImages.test.js
  server/test/molecules_importation/analyzer/files/duplicatesMolecules.csv
  server/test/molecules_importation/analyzer/moleculesAnalyzer.test.js
  server/test/molecules_importation/importation_route/importMolecule.test.js
  server/test/required_data/users.sql
  server/test/users_importation/analyzer/files/close_logins.csv
  server/test/users_importation/analyzer/files/duplicates_login.csv
  server/test/users_importation/analyzer/files/invalid_admin.csv
  server/test/users_importation/analyzer/files/invalid_login.csv
  server/test/users_importation/analyzer/files/no_admins.csv
  server/test/users_importation/analyzer/files/no_users.csv
  server/test/users_importation/analyzer/files/students.csv
  server/test/users_importation/analyzer/files/worst.csv
  server/test/users_importation/analyzer/usersAnalyzer.test.js
  server/test/users_importation/importation_route/files/bad.csv
  server/test/users_importation/importation_route/files/small.csv
  server/test/users_importation/importation_route/files/users.csv
  server/test/users_importation/importation_route/files/users.xlsx
  server/test/users_importation/importation_route/importUsers.test.js
  server/test/users_importation/importer/expectations.js
  server/test/users_importation/importer/files/close_logins.csv
  server/test/users_importation/importer/files/duplicates_login.csv
  server/test/users_importation/importer/files/invalid_admin.csv
  server/test/users_importation/importer/files/invalid_login.csv
  server/test/users_importation/importer/files/no_admins.csv
  server/test/users_importation/importer/files/no_users.csv
  server/test/users_importation/importer/files/small.csv
  server/test/users_importation/importer/files/students.csv
  server/test/users_importation/importer/files/worst.csv
  server/test/users_importation/importer/usersImporter.test.js
  server/test/users_importation/parser/files/students.csv
  server/test/users_importation/parser/usersParser.test.js
Labels: Backend, Database

#194 Rename PWA to guacamole
  client/public/manifest.json
Labels: Frontend

#199 Updated package-lock.json to lockfileVersion: 2
  client/package-lock.json
  package-lock.json
  server/package-lock.json
Labels: dependencies

#202 Increase max waiting time before running the tests
  server/test/index.test.js
Labels: CI/CD/Github

#187 Add cache for API requests
  client/package-lock.json
  client/package.json
  client/src/App.js
  client/src/components/AvatarChooser.js
  client/src/components/ChooseAvatar.js
  client/src/components/status/FloatingError.js
  client/src/components/status/Loading.js
  client/src/components/status/PageError.js
  client/src/components/system/TopBar.js
  client/src/pages/About.js
  client/src/pages/CreateDuel.js
  client/src/pages/DuelOverview.js
  client/src/pages/HomePage.js
  client/src/pages/Profile.js
  client/src/utils/configuredQueryClient.js
  client/src/utils/queryDuels.js
  client/src/utils/queryUsers.js
  githooks/pre-commit.sh
  server/controllers/user.js
  server/package-lock.json
  server/package.json
Labels: Frontend

#196 Duel configuration
  client/package-lock.json
  client/src/pages/Admin.js
  client/src/pages/Duel.js
  client/src/pages/Train.js
  client/src/styles/base/_shared.scss
  client/src/styles/pages/_Admin.scss
  server/controllers/config.js
  server/controllers/duels.js
  server/controllers/imagesImporter.js
  server/controllers/moleculesImporter.js
  server/controllers/question.js
  server/db/database.js
  server/db/updates/db_20210219_to_20210222.sql
  server/routes/api.route.js
  server/test/config/config.test.js
  server/test/config/files/molecules_empty.csv
  server/test/config/files/molecules_little_sample.csv
  server/test/config/files/molecules_no_properties.csv
  server/test/database.test.js
  server/test/duel.test.js
  server/test/index.test.js
  server/test/required_data/config.sql
Labels: Backend, Database, Frontend

#204 <Redirect/> instead of location.replace()
  client/src/App.js
  client/src/components/system/TopBar.js
  client/src/pages/Duel.js
  client/src/pages/DuelCreate.js
  client/src/pages/HomePage.js
  client/src/pages/Login.js
  client/src/pages/Menu.js
  client/src/pages/Profile.js
  client/src/services/auth.service.js
  client/src/styles/pages/_DuelCreate.scss
  client/src/styles/styles.scss
Labels: Frontend
